// examples/dsl-v2-basic/src/screens/BacklogScreen.tsx
import type { MessageHistoryEntry } from "../message-history.js";

interface BacklogScreenProps {
  readonly entries: readonly MessageHistoryEntry[];
  readonly onBack: () => void;
}

export function BacklogScreen({ entries, onBack }: BacklogScreenProps) {
  return (
    <section className="screen" aria-label="Backlog">
      <div className="screen__content screen__content--panel">
        <h1 className="screen__heading">Backlog</h1>
        <div className="backlog">
          {entries.length === 0 ? (
            <p className="backlog__empty">No backlog yet.</p>
          ) : (
            <ol className="backlog__list">
              {entries.map((entry) => (
                <li key={entry.id} className="backlog__entry">
                  {entry.kind === "dialogue" && entry.speakerName !== null ? (
                    <p className="backlog__speaker">{entry.speakerName}</p>
                  ) : null}
                  <p className="backlog__text">{entry.text}</p>
                </li>
              ))}
            </ol>
          )}
        </div>
        <button type="button" className="screen__button" onClick={onBack}>
          Back
        </button>
      </div>
    </section>
  );
}

// examples/vue-basic/src/screens/BacklogScreen.vue
<script setup lang="ts">
defineProps<{
  readonly entries: readonly {
    readonly speaker: string | null;
    readonly text: string;
  }[];
}>();
const emit = defineEmits<{
  back: [];
}>();
</script>

<template>
  <section class="screen screen--panel">
    <div class="screen__inner panel-screen">
      <h1>Backlog</h1>
      <ol v-if="entries.length > 0" class="backlog-list">
        <li v-for="(entry, index) in entries" :key="index" class="backlog-list__entry">
          <p v-if="entry.speaker !== null" class="backlog-list__speaker">{{ entry.speaker }}</p>
          <p>{{ entry.text }}</p>
        </li>
      </ol>
      <p v-else class="panel-screen__empty">No messages yet.</p>
      <button type="button" @click="emit('back')">Back</button>
    </div>
  </section>
</template>
