// examples/standard-ui-preact/src/App.tsx
import { useCallback, useMemo, useState } from "preact/hooks";
import {
  compileTzr,
  parseTzr,
  type CompiledTzrDocument,
  type RuntimeDiagnostic,
} from "@tsuzuru/core";
import {
  createStdAudioCommandHandlers,
  createStdAudioPlugin,
  stdAudioPluginCommands,
} from "@tsuzuru/plugin-std-audio";
import {
  createStdVisualCommandHandlers,
  createStdVisualPlugin,
  stdVisualPluginCommands,
} from "@tsuzuru/plugin-std-visual";
import { useRuntime } from "@tsuzuru/preact";
import {
  GameShell,
  GameViewport,
  RuntimeMessageLayer,
  ScreenHost,
  type ActiveScreen,
} from "@tsuzuru/standard-ui-preact";
import scenarioSource from "../scenario/main.tzr?raw";
import { AudioLayer } from "./AudioLayer.js";
import { screens } from "./screens.js";
import { VisualLayer } from "./VisualLayer.js";

type DocumentResult =
  | { readonly ok: true; readonly document: CompiledTzrDocument }
  | { readonly ok: false; readonly message: string };

const AUTO_STEP_MAX_STEPS = 1000;

export function App() {
  const documentResult = useMemo(() => compileScenario(scenarioSource), []);

  if (!documentResult.ok) {
    return <pre className="app app--error">{documentResult.message}</pre>;
  }

  return <RuntimeApp document={documentResult.document} />;
}

interface RuntimeAppProps {
  readonly document: CompiledTzrDocument;
}

function RuntimeApp({ document }: RuntimeAppProps) {
  const [diagnostics, setDiagnostics] = useState<readonly RuntimeDiagnostic[]>([]);
  const [activeScreen, setActiveScreen] = useState<ActiveScreen | null>(null);
  const plugins = useMemo(() => [createStdVisualPlugin(), createStdAudioPlugin()], []);
  const commandHandlers = useMemo(
    () => ({
      ...createStdVisualCommandHandlers(),
      ...createStdAudioCommandHandlers(),
    }),
    [],
  );
  const recordDiagnostic = useCallback((diagnostic: RuntimeDiagnostic) => {
    setDiagnostics((current) => [...current, diagnostic]);
  }, []);
  const runtime = useRuntime(document, {
    plugins,
    commandHandlers,
    onDiagnostic: recordDiagnostic,
    autoStepTransientEvents: true,
    autoStepMaxSteps: AUTO_STEP_MAX_STEPS,
  });
  const canAdvanceText =
    (runtime.visibleEvent?.type === "narration" || runtime.visibleEvent?.type === "dialogue") &&
    !runtime.isBlocked &&
    !runtime.state.isStopped;

  const advanceText = () => {
    if (canAdvanceText) {
      runtime.step();
    }
  };

  const reset = () => {
    setDiagnostics([]);
    setActiveScreen(null);
    runtime.reset();
  };

  const openNotebook = () => {
    setActiveScreen({ id: "notebook", params: { title: "Notebook" } });
  };

  return (
    <main className="app">
      <header className="app__header">
        <h1>Tsuzuru standard-ui-preact</h1>
        <p>Standard message UI with example-local visual and audio layers.</p>
      </header>
      <GameViewport aspectRatio="16:9" maxWidth={960}>
        <GameShell className="app__shell">
          <VisualLayer runtimeState={runtime.state} />
          <AudioLayer runtimeState={runtime.state} />
          <div className="app__message-layer">
            {runtime.visibleEvent === null ? (
              <p className="app__placeholder">Press Debug Step to start.</p>
            ) : (
              <RuntimeMessageLayer
                event={runtime.visibleEvent}
                onChoice={runtime.choose}
                onContinue={runtime.continueClick}
                onAdvance={advanceText}
                canAdvance={canAdvanceText}
              />
            )}
          </div>
          <ScreenHost activeScreen={activeScreen} screens={screens} onClose={() => setActiveScreen(null)} />
        </GameShell>
      </GameViewport>
      <div className="app__controls">
        <button
          type="button"
          onClick={runtime.step}
          disabled={runtime.isBlocked || runtime.state.isStopped || runtime.event?.type === "end"}
        >
          Debug Step
        </button>
        <button type="button" onClick={reset}>
          Reset
        </button>
        <button type="button" onClick={openNotebook}>
          Open Notebook
        </button>
      </div>
      {runtime.autoStepError === null ? null : <p className="app__runtime-error">{runtime.autoStepError}</p>}
      {diagnostics.length === 0 ? null : (
        <ul className="app__diagnostics">
          {diagnostics.map((diagnostic, index) => (
            <li key={`${diagnostic.code}:${index}`}>{diagnostic.message}</li>
          ))}
        </ul>
      )}
    </main>
  );
}

function compileScenario(source: string): DocumentResult {
  const parsed = parseTzr(source, { filePath: "examples/standard-ui-preact/scenario/main.tzr" });
  if (!parsed.ok) {
    return { ok: false, message: formatDiagnostics(parsed.errors) };
  }

  const compiled = compileTzr(parsed.document, {
    pluginCommands: {
      ...stdVisualPluginCommands,
      ...stdAudioPluginCommands,
    },
  });
  if (!compiled.ok) {
    return { ok: false, message: formatDiagnostics(compiled.errors) };
  }

  return { ok: true, document: compiled.document };
}

interface DiagnosticLike {
  readonly message: string;
}

function formatDiagnostics(diagnostics: readonly DiagnosticLike[]): string {
  return diagnostics.map((diagnostic) => diagnostic.message).join("\n");
}

// examples/vue-basic/src/App.vue
<script setup lang="ts">
import type { CompiledTzrDocument, RuntimeDiagnostic, RuntimeEvent, RuntimePluginDefinition } from "@tsuzuru/core";
import { createStdAudioCommandHandlers, createStdAudioPlugin } from "@tsuzuru/plugin-std-audio";
import { createStdVisualCommandHandlers, createStdVisualPlugin } from "@tsuzuru/plugin-std-visual";
import { useRuntime } from "@tsuzuru/vue";
import { computed, ref, watch } from "vue";
import AudioLayer from "./components/AudioLayer.vue";
import ChoiceLayer from "./components/ChoiceLayer.vue";
import MessageWindow from "./components/MessageWindow.vue";
import RuntimeControlBar from "./components/RuntimeControlBar.vue";
import VisualLayer from "./components/VisualLayer.vue";
import { scenarioProject } from "./scenario.js";
import BacklogScreen from "./screens/BacklogScreen.vue";
import GalleryScreen from "./screens/GalleryScreen.vue";
import SettingsScreen from "./screens/SettingsScreen.vue";
import TitleScreen from "./screens/TitleScreen.vue";

type DocumentResult =
  | { readonly ok: true; readonly document: CompiledTzrDocument }
  | { readonly ok: false; readonly message: string };
type AppScreen = "title" | "runtime" | "backlog" | "settings" | "gallery";
type MessageEvent = Extract<RuntimeEvent, { type: "narration" | "dialogue" }>;

interface BacklogEntry {
  readonly speaker: string | null;
  readonly text: string;
}

interface Preferences {
  readonly messageScale: number;
  readonly showAudioNotices: boolean;
}

const documentResult: DocumentResult = scenarioProject.ok
  ? { ok: true, document: scenarioProject.document }
  : { ok: false, message: formatDiagnostics(scenarioProject.errors) };
const screen = ref<AppScreen>("title");
const preferences = ref<Preferences>({
  messageScale: 1,
  showAudioNotices: true,
});
const diagnostics = ref<readonly RuntimeDiagnostic[]>([]);
const audioNotices = ref<readonly string[]>([]);
const backlog = ref<readonly BacklogEntry[]>([]);

const plugins: readonly RuntimePluginDefinition[] = [createStdVisualPlugin(), createStdAudioPlugin()];
const commandHandlers = {
  ...createStdVisualCommandHandlers(),
  ...createStdAudioCommandHandlers(),
};
const runtime = documentResult.ok
  ? useRuntime(documentResult.document, {
      plugins,
      commandHandlers,
      autoClearWait: true,
      autoStepTransientEvents: true,
      onDiagnostic: (diagnostic) => {
        diagnostics.value = [...diagnostics.value, diagnostic];
      },
    })
  : null;

const visibleEvent = computed(() => runtime?.visibleEvent.value ?? null);
const choiceEvent = computed(() => (visibleEvent.value?.type === "choice" ? visibleEvent.value : null));
const messageEvent = computed<MessageEvent | null>(() =>
  visibleEvent.value?.type === "narration" || visibleEvent.value?.type === "dialogue" ? visibleEvent.value : null,
);
const runtimeStatus = computed(() => {
  if (runtime === null) {
    return "Scenario unavailable";
  }
  if (runtime.autoStepError.value !== null) {
    return runtime.autoStepError.value;
  }
  if (runtime.blockReason.value !== null) {
    return `Blocked: ${runtime.blockReason.value}`;
  }
  if (runtime.state.value.isStopped) {
    return "Stopped";
  }
  return runtime.event.value === null ? "Ready" : `Event: ${runtime.event.value.type}`;
});

watch(
  messageEvent,
  (event) => {
    if (event === null) {
      return;
    }

    backlog.value = [
      ...backlog.value,
      {
        speaker: event.type === "dialogue" ? event.speaker : null,
        text: event.lines.map((line) => line.text).join("\n"),
      },
    ];
  },
  { flush: "sync" },
);

function startRuntime(): void {
  if (runtime === null) {
    return;
  }

  backlog.value = [];
  diagnostics.value = [];
  audioNotices.value = [];
  runtime.reset();
  screen.value = "runtime";
  runtime.step();
}

function advanceRuntime(): void {
  const event = visibleEvent.value;
  if (runtime === null || event === null) {
    return;
  }

  switch (event.type) {
    case "narration":
    case "dialogue":
    case "page":
      runtime.step();
      return;
    case "waitClick":
      runtime.continueClick();
      return;
    case "choice":
    case "wait":
    case "end":
    case "stop":
    case "unsupported":
    case "error":
      return;
    default:
      runtime.step();
  }
}

function chooseRuntimeItem(itemIndex: number): void {
  runtime?.choose(itemIndex);
}

function updatePreferences(nextPreferences: Preferences): void {
  preferences.value = nextPreferences;
}

function addAudioNotice(message: string): void {
  audioNotices.value = [...audioNotices.value.slice(-4), message];
}

function formatDiagnostics(errors: readonly { readonly message: string }[]): string {
  return errors.map((error) => error.message).join("\n");
}
</script>

<template>
  <main class="app">
    <pre v-if="!documentResult.ok" class="app__error">{{ documentResult.message }}</pre>

    <TitleScreen
      v-else-if="screen === 'title'"
      :can-open-backlog="backlog.length > 0"
      @start="startRuntime"
      @backlog="screen = 'backlog'"
      @settings="screen = 'settings'"
      @gallery="screen = 'gallery'"
    />

    <BacklogScreen
      v-else-if="screen === 'backlog'"
      :entries="backlog"
      @back="screen = runtime === null || runtime.event.value === null ? 'title' : 'runtime'"
    />

    <SettingsScreen
      v-else-if="screen === 'settings'"
      :preferences="preferences"
      @change="updatePreferences"
      @back="screen = runtime === null || runtime.event.value === null ? 'title' : 'runtime'"
    />

    <GalleryScreen v-else-if="screen === 'gallery'" @back="screen = 'title'" />

    <section v-else class="runtime-screen" @click.self="advanceRuntime">
      <VisualLayer v-if="runtime !== null" :state="runtime.state.value" />
      <AudioLayer
        v-if="runtime !== null"
        :state="runtime.state.value"
        :event="runtime.event.value"
        @notice="addAudioNotice"
      />
      <RuntimeControlBar
        :status="runtimeStatus"
        @title="screen = 'title'"
        @backlog="screen = 'backlog'"
        @settings="screen = 'settings'"
        @gallery="screen = 'gallery'"
        @step="advanceRuntime"
        @reset="startRuntime"
      />
      <div class="runtime-screen__diagnostics" v-if="diagnostics.length > 0">
        <p v-for="diagnostic in diagnostics" :key="`${diagnostic.code}:${diagnostic.message}`">
          {{ diagnostic.message }}
        </p>
      </div>
      <div class="runtime-screen__audio-notices" v-if="preferences.showAudioNotices && audioNotices.length > 0">
        <p v-for="notice in audioNotices" :key="notice">{{ notice }}</p>
      </div>
      <MessageWindow
        :event="visibleEvent"
        :message-scale="preferences.messageScale"
        @advance="advanceRuntime"
      />
      <ChoiceLayer :event="choiceEvent" @choose="chooseRuntimeItem" />
    </section>
  </main>
</template>
