// examples/vue-basic/src/components/ParticleLayer.vue
<script setup lang="ts">
import type { RuntimeState } from "@tsuzuru/core";
import { getStdParticleState } from "@tsuzuru/plugin-std-particle";
import { computed } from "vue";
import { getParticleSpecs, particleLayerClassName, particleStyleProperties } from "../particle-presentation.js";

const props = defineProps<{
  readonly state: RuntimeState;
}>();

const particleState = computed(() => getStdParticleState(props.state));
const current = computed(() => particleState.value.current);
const particles = computed(() =>
  current.value === null ? [] : getParticleSpecs(current.value.type, current.value.intensity),
);
const className = computed(() => (current.value === null ? "particle-layer" : particleLayerClassName(current.value)));
</script>

<template>
  <div v-if="current !== null" :class="className" aria-hidden="true">
    <span
      v-for="particle in particles"
      :key="particle.id"
      class="particle-layer__particle"
      :style="particleStyleProperties(particle)"
    />
  </div>
</template>

// examples/preact-basic/src/ParticleLayer.tsx
import type { RuntimeState } from "@tsuzuru/core";
import { getStdParticleState } from "@tsuzuru/plugin-std-particle";
import {
  getParticleSpecs,
  type ParticleStyleProperties,
  particleLayerClassName,
  particleStyleProperties,
} from "./particle-presentation.js";

interface ParticleLayerProps {
  readonly runtimeState: RuntimeState;
}

export function ParticleLayer({ runtimeState }: ParticleLayerProps) {
  const particleState = getStdParticleState(runtimeState);
  const current = particleState.current;

  if (current === null) {
    return null;
  }

  const particles = getParticleSpecs(current.type, current.intensity);

  return (
    <div className={particleLayerClassName(current)} aria-hidden="true">
      {particles.map((particle) => (
        <span
          key={particle.id}
          className="particle-layer__particle"
          style={particleStyleProperties(particle) as ParticleStyleProperties}
        />
      ))}
    </div>
  );
}
