// examples/vue-basic/src/App.vue
<script setup lang="ts">
import type { CompiledTzrDocument, RuntimeDiagnostic, RuntimeEvent, RuntimePluginDefinition } from "@tsuzuru/core";
import { createStdAudioCommandHandlers, createStdAudioPlugin } from "@tsuzuru/plugin-std-audio";
import { createStdVisualCommandHandlers, createStdVisualPlugin } from "@tsuzuru/plugin-std-visual";
import { useRuntime } from "@tsuzuru/vue";
import { computed, ref, watch } from "vue";
import AudioLayer from "./components/AudioLayer.vue";
import ChoiceLayer from "./components/ChoiceLayer.vue";
import MessageWindow from "./components/MessageWindow.vue";
import RuntimeControlBar from "./components/RuntimeControlBar.vue";
import VisualLayer from "./components/VisualLayer.vue";
import { scenarioProject } from "./scenario.js";
import BacklogScreen from "./screens/BacklogScreen.vue";
import GalleryScreen from "./screens/GalleryScreen.vue";
import SettingsScreen from "./screens/SettingsScreen.vue";
import TitleScreen from "./screens/TitleScreen.vue";

type DocumentResult =
  | { readonly ok: true; readonly document: CompiledTzrDocument }
  | { readonly ok: false; readonly message: string };
type AppScreen = "title" | "runtime" | "backlog" | "settings" | "gallery";
type MessageEvent = Extract<RuntimeEvent, { type: "narration" | "dialogue" }>;

interface BacklogEntry {
  readonly speaker: string | null;
  readonly text: string;
}

interface Preferences {
  readonly messageScale: number;
  readonly showAudioNotices: boolean;
}

const documentResult: DocumentResult = scenarioProject.ok
  ? { ok: true, document: scenarioProject.document }
  : { ok: false, message: formatDiagnostics(scenarioProject.errors) };
const screen = ref<AppScreen>("title");
const preferences = ref<Preferences>({
  messageScale: 1,
  showAudioNotices: true,
});
const diagnostics = ref<readonly RuntimeDiagnostic[]>([]);
const audioNotices = ref<readonly string[]>([]);
const backlog = ref<readonly BacklogEntry[]>([]);

const plugins: readonly RuntimePluginDefinition[] = [createStdVisualPlugin(), createStdAudioPlugin()];
const commandHandlers = {
  ...createStdVisualCommandHandlers(),
  ...createStdAudioCommandHandlers(),
};
const runtime = documentResult.ok
  ? useRuntime(documentResult.document, {
      plugins,
      commandHandlers,
      autoClearWait: true,
      autoStepTransientEvents: true,
      onDiagnostic: (diagnostic) => {
        diagnostics.value = [...diagnostics.value, diagnostic];
      },
    })
  : null;

const visibleEvent = computed(() => runtime?.visibleEvent.value ?? null);
const choiceEvent = computed(() => (visibleEvent.value?.type === "choice" ? visibleEvent.value : null));
const messageEvent = computed<MessageEvent | null>(() =>
  visibleEvent.value?.type === "narration" || visibleEvent.value?.type === "dialogue" ? visibleEvent.value : null,
);
const runtimeStatus = computed(() => {
  if (runtime === null) {
    return "Scenario unavailable";
  }
  if (runtime.autoStepError.value !== null) {
    return runtime.autoStepError.value;
  }
  if (runtime.blockReason.value !== null) {
    return `Blocked: ${runtime.blockReason.value}`;
  }
  if (runtime.state.value.isStopped) {
    return "Stopped";
  }
  return runtime.event.value === null ? "Ready" : `Event: ${runtime.event.value.type}`;
});

watch(
  messageEvent,
  (event) => {
    if (event === null) {
      return;
    }

    backlog.value = [
      ...backlog.value,
      {
        speaker: event.type === "dialogue" ? event.speaker : null,
        text: event.lines.map((line) => line.text).join("\n"),
      },
    ];
  },
  { flush: "sync" },
);

function startRuntime(): void {
  if (runtime === null) {
    return;
  }

  backlog.value = [];
  diagnostics.value = [];
  audioNotices.value = [];
  runtime.reset();
  screen.value = "runtime";
  runtime.step();
}

function advanceRuntime(): void {
  const event = visibleEvent.value;
  if (runtime === null || event === null) {
    return;
  }

  switch (event.type) {
    case "narration":
    case "dialogue":
    case "page":
      runtime.step();
      return;
    case "waitClick":
      runtime.continueClick();
      return;
    case "choice":
    case "wait":
    case "end":
    case "stop":
    case "unsupported":
    case "error":
      return;
    default:
      runtime.step();
  }
}

function chooseRuntimeItem(itemIndex: number): void {
  runtime?.choose(itemIndex);
}

function updatePreferences(nextPreferences: Preferences): void {
  preferences.value = nextPreferences;
}

function addAudioNotice(message: string): void {
  audioNotices.value = [...audioNotices.value.slice(-4), message];
}

function formatDiagnostics(errors: readonly { readonly message: string }[]): string {
  return errors.map((error) => error.message).join("\n");
}
</script>

<template>
  <main class="app">
    <pre v-if="!documentResult.ok" class="app__error">{{ documentResult.message }}</pre>

    <TitleScreen
      v-else-if="screen === 'title'"
      :can-open-backlog="backlog.length > 0"
      @start="startRuntime"
      @backlog="screen = 'backlog'"
      @settings="screen = 'settings'"
      @gallery="screen = 'gallery'"
    />

    <BacklogScreen
      v-else-if="screen === 'backlog'"
      :entries="backlog"
      @back="screen = runtime === null || runtime.event.value === null ? 'title' : 'runtime'"
    />

    <SettingsScreen
      v-else-if="screen === 'settings'"
      :preferences="preferences"
      @change="updatePreferences"
      @back="screen = runtime === null || runtime.event.value === null ? 'title' : 'runtime'"
    />

    <GalleryScreen v-else-if="screen === 'gallery'" @back="screen = 'title'" />

    <section v-else class="runtime-screen" @click.self="advanceRuntime">
      <VisualLayer v-if="runtime !== null" :state="runtime.state.value" />
      <AudioLayer
        v-if="runtime !== null"
        :state="runtime.state.value"
        :event="runtime.event.value"
        @notice="addAudioNotice"
      />
      <RuntimeControlBar
        :status="runtimeStatus"
        @title="screen = 'title'"
        @backlog="screen = 'backlog'"
        @settings="screen = 'settings'"
        @gallery="screen = 'gallery'"
        @step="advanceRuntime"
        @reset="startRuntime"
      />
      <div class="runtime-screen__diagnostics" v-if="diagnostics.length > 0">
        <p v-for="diagnostic in diagnostics" :key="`${diagnostic.code}:${diagnostic.message}`">
          {{ diagnostic.message }}
        </p>
      </div>
      <div class="runtime-screen__audio-notices" v-if="preferences.showAudioNotices && audioNotices.length > 0">
        <p v-for="notice in audioNotices" :key="notice">{{ notice }}</p>
      </div>
      <MessageWindow
        :event="visibleEvent"
        :message-scale="preferences.messageScale"
        @advance="advanceRuntime"
      />
      <ChoiceLayer :event="choiceEvent" @choose="chooseRuntimeItem" />
    </section>
  </main>
</template>

// examples/dsl-v2-basic/src/App.tsx
import type { CompiledTzrDocument, RuntimeDiagnostic, RuntimeEvent, RuntimePluginDefinition } from "@tsuzuru/core";
import { createStdAudioCommandHandlers, createStdAudioPlugin } from "@tsuzuru/plugin-std-audio";
import { createStdVisualCommandHandlers, createStdVisualPlugin } from "@tsuzuru/plugin-std-visual";
import { getRenderableRuntimeEvent, useRuntime } from "@tsuzuru/preact";
import {
  ChoiceLayer,
  GameShell,
  GameViewport,
  type MessageWindowRenderLineContext,
  RuntimeMessageLayer,
  useTextReveal,
} from "@tsuzuru/standard-ui-preact";
import type { ComponentChildren, ComponentProps } from "preact";
import { useCallback, useEffect, useMemo, useRef, useState } from "preact/hooks";
import { AudioLayer } from "./AudioLayer.js";
import { scenarioProject } from "./scenario.js";
import { BacklogScreen } from "./screens/BacklogScreen.js";
import { GalleryScreen } from "./screens/GalleryScreen.js";
import { LoadScreen } from "./screens/LoadScreen.js";
import { SettingsScreen } from "./screens/SettingsScreen.js";
import { TitleScreen } from "./screens/TitleScreen.js";
import { VisualLayer } from "./VisualLayer.js";

type DocumentResult =
  | { readonly ok: true; readonly document: CompiledTzrDocument }
  | { readonly ok: false; readonly message: string };
type DivClickHandler = NonNullable<ComponentProps<"div">["onClick"]>;
type AppScreen = "title" | "runtime" | "load" | "settings" | "backlog" | "gallery";

export function App() {
  const documentResult = useMemo((): DocumentResult => {
    if (!scenarioProject.ok) {
      return { ok: false, message: formatDiagnostics(scenarioProject.errors) };
    }
    return { ok: true, document: scenarioProject.document };
  }, []);
  const [screen, setScreen] = useState<AppScreen>("title");

  if (!documentResult.ok) {
    return <pre className="app app--error">{documentResult.message}</pre>;
  }

  if (screen === "runtime") {
    return (
      <RuntimeApp
        document={documentResult.document}
        onTitle={() => setScreen("title")}
        onSettings={() => setScreen("settings")}
        onBacklog={() => setScreen("backlog")}
      />
    );
  }

  return (
    <ScreenFrame>
      {screen === "title" ? (
        <TitleScreen
          onStart={() => setScreen("runtime")}
          onLoad={() => setScreen("load")}
          onSettings={() => setScreen("settings")}
          onBacklog={() => setScreen("backlog")}
          onGallery={() => setScreen("gallery")}
        />
      ) : screen === "load" ? (
        <LoadScreen onBack={() => setScreen("title")} />
      ) : screen === "settings" ? (
        <SettingsScreen onBack={() => setScreen("title")} />
      ) : screen === "backlog" ? (
        <BacklogScreen onBack={() => setScreen("title")} />
      ) : (
        <GalleryScreen onBack={() => setScreen("title")} />
      )}
    </ScreenFrame>
  );
}

interface RuntimeAppProps {
  readonly document: CompiledTzrDocument;
  readonly onTitle: () => void;
  readonly onSettings: () => void;
  readonly onBacklog: () => void;
}

function ScreenFrame({ children }: { readonly children: ComponentChildren }) {
  return (
    <main className="app">
      <GameViewport aspectRatio="16:9" className="app__viewport" maxWidth="100vw">
        <GameShell className="app__shell">{children}</GameShell>
      </GameViewport>
    </main>
  );
}

function RuntimeApp({ document, onTitle, onSettings, onBacklog }: RuntimeAppProps) {
  const plugins = useMemo<readonly RuntimePluginDefinition[]>(
    () => [createStdVisualPlugin(), createStdAudioPlugin()],
    [],
  );
  const commandHandlers = useMemo(
    () => ({
      ...createStdVisualCommandHandlers(),
      ...createStdAudioCommandHandlers(),
    }),
    [],
  );
  const [diagnostics, setDiagnostics] = useState<readonly RuntimeDiagnostic[]>([]);
  const recordDiagnostic = useCallback((diagnostic: RuntimeDiagnostic) => {
    setDiagnostics((current) => [...current, diagnostic]);
  }, []);
  const runtime = useRuntime(document, {
    plugins,
    commandHandlers,
    onDiagnostic: recordDiagnostic,
    autoClearWait: true,
    autoStepTransientEvents: true,
  });
  const [lastMessageEvent, setLastMessageEvent] = useState<RuntimeEvent | null>(null);
  const visiblePresentationEvent = toExamplePresentationEvent(runtime.visibleEvent);
  const choiceEvent = runtime.visibleEvent?.type === "choice" ? runtime.visibleEvent : null;
  const retainedMessageEvent = runtime.visibleEvent?.type === "wait" ? lastMessageEvent : null;
  const presentationKey = useVisibleEventPresentationKey(runtime.visibleEvent);
  const currentRenderableEvent = runtime.event === null ? null : getRenderableRuntimeEvent(runtime.event);
  const messageLines = useMemo(
    () => (visiblePresentationEvent === null ? null : getMessageLines(visiblePresentationEvent)),
    [visiblePresentationEvent],
  );
  const revealText = messageLines?.join("\n") ?? "";
  const lineRanges = useMemo(() => (messageLines === null ? [] : buildLineRanges(messageLines)), [messageLines]);
  const textReveal = useTextReveal(revealText, {
    enabled: messageLines !== null,
    charactersPerSecond: 60,
  });
  const canAdvanceText =
    visiblePresentationEvent !== null &&
    isMessageEvent(visiblePresentationEvent) &&
    currentRenderableEvent === runtime.visibleEvent &&
    runtime.blockReason === null &&
    !runtime.state.isStopped;
  const canStart =
    runtime.visibleEvent === null && runtime.event === null && runtime.blockReason === null && !runtime.state.isStopped;
  const handleAdvanceRequest = useCallback(() => {
    if (choiceEvent !== null) {
      return;
    }
    if (messageLines !== null) {
      if (textReveal.isRevealing) {
        textReveal.revealAll();
        return;
      }
      if (canAdvanceText) {
        runtime.step();
      }
      return;
    }
    if (canStart) {
      runtime.step();
    }
  }, [canAdvanceText, canStart, choiceEvent, messageLines, runtime, textReveal.isRevealing, textReveal.revealAll]);
  const handleViewportClick = useCallback<DivClickHandler>(
    (event) => {
      if (isInteractiveClickTarget(event.target)) {
        return;
      }
      handleAdvanceRequest();
    },
    [handleAdvanceRequest],
  );
  const renderMessageLine = useCallback(
    ({ line, lineIndex }: MessageWindowRenderLineContext) => {
      const range = lineRanges[lineIndex];
      if (range === undefined) {
        return line;
      }
      return (
        <span>{textReveal.visibleText.slice(range.start, Math.min(range.end, textReveal.visibleText.length))}</span>
      );
    },
    [lineRanges, textReveal.visibleText],
  );

  useEffect(() => {
    textReveal.reset();
  }, [presentationKey, textReveal.reset]);

  useEffect(() => {
    if (runtime.visibleEvent !== null && isMessageEvent(runtime.visibleEvent)) {
      setLastMessageEvent(runtime.visibleEvent);
    }
  }, [runtime.visibleEvent]);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.defaultPrevented || isKeyboardHandledTarget(event.target)) {
        return;
      }
      if (event.key !== "Enter" && event.key !== " ") {
        return;
      }
      event.preventDefault();
      handleAdvanceRequest();
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [handleAdvanceRequest]);

  return (
    <main className="app">
      <GameViewport aspectRatio="16:9" className="app__viewport" maxWidth="100vw">
        <GameShell className="app__shell">
          <div className="app__interaction-surface" onClick={handleViewportClick}>
            <VisualLayer runtimeState={runtime.state} />
            <AudioLayer runtimeState={runtime.state} />
            <nav className="app__runtime-menu" aria-label="Runtime menu">
              <button type="button" onClick={onBacklog}>
                Backlog
              </button>
              <button type="button" onClick={onSettings}>
                Settings
              </button>
              <button type="button" onClick={onTitle}>
                Title
              </button>
            </nav>
            <div className="app__message-layer">
              {canStart ? null : choiceEvent !== null ? (
                <>
                  <ChoiceLayer
                    className="app__choice-layer"
                    question={choiceEvent.question}
                    choices={choiceEvent.items.map((item) => ({ text: item.text }))}
                    onChoice={runtime.choose}
                  />
                  {lastMessageEvent === null ? null : (
                    <RuntimeMessageLayer
                      key={getRuntimeEventTextKey(lastMessageEvent)}
                      className="app__retained-message"
                      event={lastMessageEvent}
                      canAdvance={false}
                    />
                  )}
                </>
              ) : retainedMessageEvent !== null ? (
                <RuntimeMessageLayer
                  key={getRuntimeEventTextKey(retainedMessageEvent)}
                  className="app__retained-message"
                  event={retainedMessageEvent}
                  canAdvance={false}
                />
              ) : visiblePresentationEvent === null ? null : (
                <RuntimeMessageLayer
                  key={presentationKey}
                  event={visiblePresentationEvent}
                  onAdvance={handleAdvanceRequest}
                  {...(messageLines === null ? {} : { renderMessageLine })}
                  canAdvance={canAdvanceText}
                />
              )}
            </div>
          </div>
        </GameShell>
      </GameViewport>
      {runtime.autoStepError === null ? null : <p className="app__runtime-error">{runtime.autoStepError}</p>}
      {diagnostics.length === 0 ? null : (
        <ul className="app__diagnostics">
          {diagnostics.map((diagnostic, index) => (
            <li key={`${diagnostic.code}:${index}`}>{diagnostic.message}</li>
          ))}
        </ul>
      )}
    </main>
  );
}

function useVisibleEventPresentationKey(event: RuntimeEvent | null): string {
  const keyRef = useRef<{
    readonly event: RuntimeEvent | null;
    readonly sequence: number;
  }>({ event: null, sequence: 0 });

  if (keyRef.current.event !== event) {
    keyRef.current = {
      event,
      sequence: keyRef.current.sequence + 1,
    };
  }

  return `${keyRef.current.sequence}:${event === null ? "none" : getRuntimeEventTextKey(event)}`;
}

interface LineRange {
  readonly start: number;
  readonly end: number;
}

function isInteractiveClickTarget(target: EventTarget | null): boolean {
  return (
    target instanceof Element &&
    target.closest(".tzr-message-window, .tzr-choice-layer, button, a, input, select, textarea") !== null
  );
}

function isKeyboardHandledTarget(target: EventTarget | null): boolean {
  return (
    target instanceof Element &&
    target.closest(".tzr-message-window, .tzr-choice-layer, button, a, input, select, textarea") !== null
  );
}

function toExamplePresentationEvent(event: RuntimeEvent | null): RuntimeEvent | null {
  if (event?.type === "wait") {
    return null;
  }
  return event;
}

function isMessageEvent(
  event: RuntimeEvent,
): event is Extract<RuntimeEvent, { readonly type: "narration" | "dialogue" }> {
  return event.type === "narration" || event.type === "dialogue";
}

function getMessageLines(event: RuntimeEvent): readonly string[] | null {
  if (!isMessageEvent(event)) {
    return null;
  }
  return event.lines.map((line) => line.text);
}

function buildLineRanges(lines: readonly string[]): readonly LineRange[] {
  const ranges: LineRange[] = [];
  let start = 0;
  for (const line of lines) {
    const end = start + line.length;
    ranges.push({ start, end });
    start = end + 1;
  }
  return ranges;
}

function getRuntimeEventTextKey(event: RuntimeEvent): string {
  if (event.type === "narration" || event.type === "dialogue") {
    return event.lines.map((line) => line.text).join("\u0000");
  }
  if (event.type === "choice") {
    return event.items.map((item) => item.text).join("\u0000");
  }
  return "";
}

interface DiagnosticLike {
  readonly message: string;
}

function formatDiagnostics(diagnostics: readonly DiagnosticLike[]): string {
  return diagnostics.map((diagnostic) => diagnostic.message).join("\n");
}
