// examples/vue-basic/src/components/VisualLayer.vue
<script setup lang="ts">
import type { RuntimeState } from "@tsuzuru/core";
import { getStdVisualState } from "@tsuzuru/plugin-std-visual";
import { computed } from "vue";
import { assets } from "../../assets.js";

const props = defineProps<{
  readonly state: RuntimeState;
}>();

const visualState = computed(() => getStdVisualState(props.state));
const background = computed(() => {
  const assetId = visualState.value.background?.assetId;
  return assetId === undefined ? null : (assets.visual.backgrounds[assetId as keyof typeof assets.visual.backgrounds] ?? null);
});
const sprites = computed(() =>
  Object.entries(visualState.value.sprites).map(([assetId, sprite]) => ({
    assetId,
    position: sprite.position,
    asset: assets.visual.sprites[assetId as keyof typeof assets.visual.sprites] ?? null,
  })),
);
</script>

<template>
  <div class="visual-layer" aria-hidden="true">
    <img v-if="background !== null" class="visual-layer__background" :src="background.url" :alt="background.label" />
    <div v-else class="visual-layer__fallback">Vue Basic</div>
    <div class="visual-layer__sprites" aria-hidden="true">
      <img
        v-for="sprite in sprites"
        :key="sprite.assetId"
        class="visual-layer__sprite"
        :class="`visual-layer__sprite--${sprite.position}`"
        :src="sprite.asset?.url"
        :alt="sprite.asset?.label ?? sprite.assetId"
      />
    </div>
  </div>
</template>

// examples/dsl-v2-basic/src/VisualLayer.tsx
import type { RuntimeState } from "@tsuzuru/core";
import { getStdVisualState, type StdVisualSpritePosition } from "@tsuzuru/plugin-std-visual";

interface VisualLayerProps {
  readonly runtimeState: RuntimeState;
}

export function VisualLayer({ runtimeState }: VisualLayerProps) {
  const visualState = getStdVisualState(runtimeState);
  const backgroundAssetId = visualState.background?.assetId ?? null;
  const sprites = Object.entries(visualState.sprites);

  return (
    <div className="visual-layer" aria-label="std-visual placeholder layer">
      <div className="visual-layer__background">
        <span>{backgroundAssetId ?? "No background"}</span>
      </div>
      <div className="visual-layer__sprites" aria-label="sprites">
        {sprites.map(([assetId, sprite]) => (
          <SpritePlaceholder key={assetId} assetId={assetId} position={sprite.position} />
        ))}
      </div>
    </div>
  );
}

function SpritePlaceholder({
  assetId,
  position,
}: {
  readonly assetId: string;
  readonly position: StdVisualSpritePosition;
}) {
  return (
    <div className={`visual-layer__sprite visual-layer__sprite--${position}`}>
      <span>{assetId}</span>
      <small>{position}</small>
    </div>
  );
}
